apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec: 
  identityProviders:
  - name: shbfc-cluser-users
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: shbfc-cluster-users

